/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.networknt.email;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EmailDeletedEvent extends org.apache.avro.specific.SpecificRecordBase implements EmailEvent {
  private static final long serialVersionUID = -2476177479673890315L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmailDeletedEvent\",\"namespace\":\"com.networknt.email\",\"fields\":[{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"A generated unique event id to identify the email\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmailDeletedEvent> ENCODER =
      new BinaryMessageEncoder<EmailDeletedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmailDeletedEvent> DECODER =
      new BinaryMessageDecoder<EmailDeletedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EmailDeletedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EmailDeletedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmailDeletedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EmailDeletedEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EmailDeletedEvent from a ByteBuffer. */
  public static EmailDeletedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** A generated unique event id to identify the email */
  @Deprecated public java.lang.String eventId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmailDeletedEvent() {}

  /**
   * All-args constructor.
   * @param eventId A generated unique event id to identify the email
   */
  public EmailDeletedEvent(java.lang.String eventId) {
    this.eventId = eventId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return A generated unique event id to identify the email
   */
  public java.lang.String getEventId() {
    return eventId;
  }

  /**
   * Sets the value of the 'eventId' field.
   * A generated unique event id to identify the email
   * @param value the value to set.
   */
  public void setEventId(java.lang.String value) {
    this.eventId = value;
  }

  /**
   * Creates a new EmailDeletedEvent RecordBuilder.
   * @return A new EmailDeletedEvent RecordBuilder
   */
  public static com.networknt.email.EmailDeletedEvent.Builder newBuilder() {
    return new com.networknt.email.EmailDeletedEvent.Builder();
  }

  /**
   * Creates a new EmailDeletedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmailDeletedEvent RecordBuilder
   */
  public static com.networknt.email.EmailDeletedEvent.Builder newBuilder(com.networknt.email.EmailDeletedEvent.Builder other) {
    return new com.networknt.email.EmailDeletedEvent.Builder(other);
  }

  /**
   * Creates a new EmailDeletedEvent RecordBuilder by copying an existing EmailDeletedEvent instance.
   * @param other The existing instance to copy.
   * @return A new EmailDeletedEvent RecordBuilder
   */
  public static com.networknt.email.EmailDeletedEvent.Builder newBuilder(com.networknt.email.EmailDeletedEvent other) {
    return new com.networknt.email.EmailDeletedEvent.Builder(other);
  }

  /**
   * RecordBuilder for EmailDeletedEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmailDeletedEvent>
    implements org.apache.avro.data.RecordBuilder<EmailDeletedEvent> {

    /** A generated unique event id to identify the email */
    private java.lang.String eventId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.networknt.email.EmailDeletedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmailDeletedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.networknt.email.EmailDeletedEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * A generated unique event id to identify the email
      * @return The value.
      */
    public java.lang.String getEventId() {
      return eventId;
    }

    /**
      * Sets the value of the 'eventId' field.
      * A generated unique event id to identify the email
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.networknt.email.EmailDeletedEvent.Builder setEventId(java.lang.String value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * A generated unique event id to identify the email
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * A generated unique event id to identify the email
      * @return This builder.
      */
    public com.networknt.email.EmailDeletedEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmailDeletedEvent build() {
      try {
        EmailDeletedEvent record = new EmailDeletedEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmailDeletedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmailDeletedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmailDeletedEvent>
    READER$ = (org.apache.avro.io.DatumReader<EmailDeletedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
